-- MySQL Script generated by MySQL Workbench
-- Wed Feb 28 21:05:26 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`title_basics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`title_basics` ;

CREATE TABLE IF NOT EXISTS `mydb`.`title_basics` (
  `tconst` INT NULL,
  `primary_title` VARCHAR(55) NULL,
  `start_year` VARCHAR(55) NULL,
  `runtime` VARCHAR(55) NULL,
  PRIMARY KEY (`tconst`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ratings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ratings` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ratings` (
  `tconst` INT NULL,
  `average_rating` VARCHAR(55) NULL,
  `number_of_votes` VARCHAR(55) NULL,
  PRIMARY KEY (`tconst`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`title_genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`title_genres` ;

CREATE TABLE IF NOT EXISTS `mydb`.`title_genres` (
  `tconst` INT NOT NULL AUTO_INCREMENT,
  `genre_id` VARCHAR(55) NULL,
  PRIMARY KEY (`tconst`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`genres` ;

CREATE TABLE IF NOT EXISTS `mydb`.`genres` (
  `genre_id` INT NOT NULL AUTO_INCREMENT,
  `genre_name` VARCHAR(55) NULL,
  PRIMARY KEY (`genre_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
